// products.js — 40 realistic glass & allied products for AmalGus marketplace

export const PRODUCTS = [
  // ── TEMPERED GLASS ──────────────────────────────────────
  {
    id: 1,
    name: "6mm Clear Tempered Safety Glass",
    category: "Tempered Glass",
    thickness: 6,
    size: "2400×1200mm (custom available)",
    color: "Clear",
    coating: "None",
    edge: "Polished",
    certification: "IS 2553 Part 2, BIS certified",
    supplier: "GuardGlass Industries",
    location: "Pune, Maharashtra",
    price: 850,
    priceUnit: "per sqm",
    minOrder: "50 sqm",
    leadTime: "7–10 days",
    description: "Toughened clear safety glass, 5× stronger than standard float glass. Heat-soaked process ensures zero spontaneous breakage. Ideal for office cabin partitions, glass doors, and interior safety glazing applications.",
    tags: ["office partition", "safety glass", "toughened", "clear", "polished edge", "interior", "door", "cabin", "IS 2553"]
  },
  {
    id: 2,
    name: "8mm Bronze Tinted Tempered Glass",
    category: "Tempered Glass",
    thickness: 8,
    size: "3000×2000mm",
    color: "Bronze",
    coating: "Heat-absorbing body tint",
    edge: "Polished",
    certification: "IS 2553",
    supplier: "SunShield Glass Works",
    location: "Chennai, Tamil Nadu",
    price: 1150,
    priceUnit: "per sqm",
    minOrder: "30 sqm",
    leadTime: "10–14 days",
    description: "Bronze tinted tempered glass reduces solar heat gain and glare. Excellent for storefronts, commercial facades, and curtain wall systems where aesthetics and sun control are needed.",
    tags: ["bronze", "tinted", "tempered", "facade", "storefront", "solar control", "commercial", "curtain wall", "heat absorbing"]
  },
  {
    id: 3,
    name: "10mm Clear Tempered Spider Glazing Glass",
    category: "Tempered Glass",
    thickness: 10,
    size: "Custom up to 3200×2100mm",
    color: "Clear",
    coating: "None",
    edge: "Polished + Drilled (spider fittings)",
    certification: "IS 2553, IS 14900",
    supplier: "SpiderGlaze Systems",
    location: "Pune, Maharashtra",
    price: 1450,
    priceUnit: "per sqm",
    minOrder: "20 sqm",
    leadTime: "14–21 days",
    description: "Extra-thick tempered glass engineered for structural point-fixed spider glazing, canopies, and frameless facade systems. Pre-drilled for spider fittings with CNC precision.",
    tags: ["spider glazing", "structural", "canopy", "facade", "frameless", "point fixed", "10mm", "drilled", "heavy duty"]
  },
  {
    id: 4,
    name: "12mm Clear Toughened Glass",
    category: "Tempered Glass",
    thickness: 12,
    size: "Custom up to 3000×2000mm",
    color: "Clear",
    coating: "None",
    edge: "Polished",
    certification: "IS 2553 Part 2",
    supplier: "StrongPane Glass",
    location: "Surat, Gujarat",
    price: 1750,
    priceUnit: "per sqm",
    minOrder: "20 sqm",
    leadTime: "10–14 days",
    description: "Heavy-duty 12mm toughened glass for structural glazing, glass floors, large frameless partitions, and high-load applications. Exceptional impact resistance.",
    tags: ["12mm", "heavy duty", "structural", "glass floor", "partition", "strong", "thick", "frameless", "high load"]
  },
  {
    id: 5,
    name: "6mm Grey Tinted Tempered Glass",
    category: "Tempered Glass",
    thickness: 6,
    size: "2440×1830mm",
    color: "Grey",
    coating: "Body tint",
    edge: "Polished",
    certification: "IS 2553",
    supplier: "ColorSafe Glass",
    location: "Hyderabad, Telangana",
    price: 920,
    priceUnit: "per sqm",
    minOrder: "40 sqm",
    leadTime: "7–12 days",
    description: "Grey tinted tempered glass provides privacy and reduces glare. Ideal for office partitions, shower cubicles, and bathroom screens where subtle tinting is preferred.",
    tags: ["grey", "tinted", "tempered", "privacy", "shower", "partition", "office", "bathroom", "subtle"]
  },
  {
    id: 6,
    name: "8mm Toughened Shower Glass with Nano Coating",
    category: "Tempered Glass",
    thickness: 8,
    size: "Custom up to 2100×900mm",
    color: "Clear",
    coating: "Nano easy-clean hydrophobic coating",
    edge: "Polished + Drilled",
    certification: "IS 2553, CE marked",
    supplier: "AquaGlass India",
    location: "Coimbatore, Tamil Nadu",
    price: 1100,
    priceUnit: "per sqm",
    minOrder: "10 sqm",
    leadTime: "7–10 days",
    description: "Frameless shower enclosure glass with nano hydrophobic easy-clean coating. Water beads off naturally, reducing cleaning effort. Pre-drilled for hinge and handle fittings.",
    tags: ["shower", "frameless", "nano coating", "easy clean", "hydrophobic", "bathroom", "drilled", "hinge", "water repellent"]
  },

  // ── LAMINATED GLASS ──────────────────────────────────────
  {
    id: 7,
    name: "8mm Clear Laminated Safety Glass (PVB)",
    category: "Laminated Glass",
    thickness: 8,
    size: "Custom up to 3000×2000mm",
    color: "Clear",
    coating: "UV-protective PVB interlayer 0.76mm",
    edge: "Polished",
    certification: "IS 2553, EN ISO 12543",
    supplier: "SafePane Solutions",
    location: "Hyderabad, Telangana",
    price: 1450,
    priceUnit: "per sqm",
    minOrder: "25 sqm",
    leadTime: "10–14 days",
    description: "4+4 PVB laminated safety glass. On breakage, fragments stay bonded to interlayer — no dangerous shards. UV-blocking PVB protects interiors from fading. Ideal for balcony railings, skylights, overhead glazing.",
    tags: ["laminated", "PVB", "safety", "balcony", "railing", "UV protection", "skylight", "overhead", "burglar resistant"]
  },
  {
    id: 8,
    name: "10mm High-Wind Laminated Glass (SentryGlas)",
    category: "Laminated Glass",
    thickness: 10,
    size: "Custom up to 3200×2100mm",
    color: "Clear",
    coating: "SentryGlas® structural interlayer",
    edge: "Polished",
    certification: "IS 2553, ASTM E1300",
    supplier: "StormSafe Glass",
    location: "Mumbai, Maharashtra",
    price: 2100,
    priceUnit: "per sqm",
    minOrder: "20 sqm",
    leadTime: "14–21 days",
    description: "5+5 structural laminated glass with SentryGlas® ionoplast interlayer. 5× stiffer than PVB — engineered for hurricane zones, coastal buildings, and high wind load balconies. Post-breakage load retention certified.",
    tags: ["high wind", "hurricane", "coastal", "structural", "SentryGlas", "balcony", "railing", "wind load", "storm resistant"]
  },
  {
    id: 9,
    name: "VSG Laminated Railing Glass 8.76mm",
    category: "Laminated Glass",
    thickness: 8.76,
    size: "Custom to spec",
    color: "Clear",
    coating: "PVB 0.76mm interlayer",
    edge: "Polished, arrised bottom edge",
    certification: "DIN 18008, IS 2553",
    supplier: "SafePane Solutions",
    location: "Hyderabad, Telangana",
    price: 1750,
    priceUnit: "per sqm",
    minOrder: "15 sqm",
    leadTime: "10–14 days",
    description: "Vertical Safety Glass specifically designed for frameless balcony railings and staircase balustrades. Certified for post-breakage safety performance — holds its shape even after impact.",
    tags: ["VSG", "railing", "balcony", "balustrade", "staircase", "frameless", "safety", "vertical", "post breakage"]
  },
  {
    id: 10,
    name: "6mm Acoustic Laminated Glass",
    category: "Laminated Glass",
    thickness: 6,
    size: "Custom up to 2800×2000mm",
    color: "Clear",
    coating: "Acoustic PVB interlayer (0.76mm)",
    edge: "Polished",
    certification: "IS 2553, STC 35dB",
    supplier: "SoundSeal Glass",
    location: "Delhi NCR",
    price: 1650,
    priceUnit: "per sqm",
    minOrder: "20 sqm",
    leadTime: "10–14 days",
    description: "Acoustic laminated glass with special sound-dampening PVB interlayer. Achieves STC 35dB sound reduction — ideal for offices near roads, airports, recording studios, and hospitals.",
    tags: ["acoustic", "soundproof", "noise reduction", "STC", "office", "hospital", "airport", "road noise", "laminated", "quiet"]
  },
  {
    id: 11,
    name: "10mm Coloured Laminated Glass — Blue",
    category: "Laminated Glass",
    thickness: 10,
    size: "Custom up to 3000×2000mm",
    color: "Blue",
    coating: "Coloured PVB interlayer",
    edge: "Polished",
    certification: "IS 2553",
    supplier: "ChromaGlass India",
    location: "Ahmedabad, Gujarat",
    price: 2300,
    priceUnit: "per sqm",
    minOrder: "15 sqm",
    leadTime: "14–18 days",
    description: "Decorative coloured laminated glass with vibrant blue PVB interlayer. Combines aesthetics with safety. Used for feature walls, reception areas, partitions, and creative architectural applications.",
    tags: ["coloured", "blue", "decorative", "feature wall", "reception", "artistic", "laminated", "safety", "creative", "interior design"]
  },

  // ── FLOAT GLASS ──────────────────────────────────────────
  {
    id: 12,
    name: "4mm Clear Float Glass",
    category: "Float Glass",
    thickness: 4,
    size: "2440×1830mm standard",
    color: "Clear",
    coating: "None",
    edge: "Cut",
    certification: "IS 2835",
    supplier: "IndiaFlat Glass Co.",
    location: "Bharuch, Gujarat",
    price: 220,
    priceUnit: "per sqm",
    minOrder: "200 sqm",
    leadTime: "3–5 days",
    description: "Standard clear float glass for residential windows, picture frames, furniture, and general glazing. Most economical option. Available in very large bulk quantities for residential projects and developers.",
    tags: ["float", "clear", "residential", "window", "budget", "economical", "bulk", "picture frame", "cheap", "4mm"]
  },
  {
    id: 13,
    name: "5mm Clear Float Glass",
    category: "Float Glass",
    thickness: 5,
    size: "2440×1830mm",
    color: "Clear",
    coating: "None",
    edge: "Cut",
    certification: "IS 2835",
    supplier: "IndiaFlat Glass Co.",
    location: "Bharuch, Gujarat",
    price: 280,
    priceUnit: "per sqm",
    minOrder: "150 sqm",
    leadTime: "3–5 days",
    description: "5mm clear float glass offering slightly better rigidity than 4mm. Suitable for larger window panes, furniture glass tops, and glazing where extra thickness provides better stability.",
    tags: ["float", "5mm", "clear", "window", "furniture", "table top", "residential", "standard", "glazing"]
  },
  {
    id: 14,
    name: "6mm Green Tinted Float Glass",
    category: "Float Glass",
    thickness: 6,
    size: "2440×1830mm",
    color: "Green",
    coating: "Body tint",
    edge: "Cut",
    certification: "IS 2835",
    supplier: "ColorGlass India",
    location: "Vadodara, Gujarat",
    price: 310,
    priceUnit: "per sqm",
    minOrder: "100 sqm",
    leadTime: "5–7 days",
    description: "Green tinted float glass reduces heat and glare while giving buildings a contemporary look. Popular for commercial windows, office buildings, and green-aesthetic architectural projects.",
    tags: ["green", "tinted", "float", "heat reduction", "glare", "commercial", "office", "building", "window", "contemporary"]
  },
  {
    id: 15,
    name: "6mm Blue Reflective Float Glass",
    category: "Float Glass",
    thickness: 6,
    size: "2440×1830mm",
    color: "Blue reflective",
    coating: "Pyrolytic hard-coat reflective coating",
    edge: "Cut / Polished",
    certification: "IS 2835",
    supplier: "ColorGlass India",
    location: "Vadodara, Gujarat",
    price: 480,
    priceUnit: "per sqm",
    minOrder: "80 sqm",
    leadTime: "5–7 days",
    description: "Reflective blue float glass for modern architectural facades. Reduces solar heat gain by 35% and provides daytime privacy from outside. Creates a striking mirror-like exterior appearance.",
    tags: ["blue", "reflective", "facade", "privacy", "solar control", "modern", "architectural", "exterior", "commercial", "daytime privacy"]
  },
  {
    id: 16,
    name: "5mm Frosted Acid Etched Glass",
    category: "Float Glass",
    thickness: 5,
    size: "2440×1830mm",
    color: "Frosted / White satin",
    coating: "Acid etched matte surface",
    edge: "Polished",
    certification: "IS 2835",
    supplier: "ArtGlass Studio",
    location: "Bengaluru, Karnataka",
    price: 650,
    priceUnit: "per sqm",
    minOrder: "20 sqm",
    leadTime: "5–8 days",
    description: "Acid-etched satin finish glass for privacy partitions, bathroom doors, and decorative panels. Diffuses natural light beautifully while blocking direct view. Non-directional etched surface.",
    tags: ["frosted", "acid etched", "satin", "privacy", "bathroom", "partition", "decorative", "diffused light", "office", "door"]
  },
  {
    id: 17,
    name: "6mm Extra Clear (Low Iron) Float Glass",
    category: "Float Glass",
    thickness: 6,
    size: "3300×2140mm",
    color: "Ultra clear / Water white",
    coating: "None",
    edge: "Polished",
    certification: "IS 2835",
    supplier: "CrystalView Glass",
    location: "Surat, Gujarat",
    price: 750,
    priceUnit: "per sqm",
    minOrder: "50 sqm",
    leadTime: "7–10 days",
    description: "Low-iron extra clear glass with 91% light transmission — no green tint. Ideal for museum display cases, luxury showcases, photo frames, aquariums, and high-end interior applications where optical clarity is critical.",
    tags: ["low iron", "ultra clear", "extra clear", "museum", "showcase", "aquarium", "optical", "clarity", "luxury", "display"]
  },

  // ── INSULATED GLASS UNITS ────────────────────────────────
  {
    id: 18,
    name: "Insulated Glass Unit 4+12+4",
    category: "Insulated Glass Unit",
    thickness: 20,
    size: "Custom up to 2500×1500mm",
    color: "Clear",
    coating: "None",
    edge: "Sealed — aluminium spacer + silicone",
    certification: "IS 13830",
    supplier: "ThermoGlass Systems",
    location: "Ahmedabad, Gujarat",
    price: 1800,
    priceUnit: "per sqm",
    minOrder: "30 sqm",
    leadTime: "12–18 days",
    description: "Entry-level double glazed IGU with 12mm air gap. Good thermal and acoustic insulation for residential windows. U-value ~2.8 W/m²K. Reduces condensation on interior glass surface.",
    tags: ["IGU", "double glazed", "insulated", "thermal", "residential", "window", "energy saving", "condensation", "acoustic"]
  },
  {
    id: 19,
    name: "Insulated Glass Unit 5+12+5 Low-E",
    category: "Insulated Glass Unit",
    thickness: 22,
    size: "Custom up to 2500×1500mm",
    color: "Clear",
    coating: "Low-E coating on surface 2",
    edge: "Sealed — PIB + silicone",
    certification: "IS 13830, EN 1279",
    supplier: "ThermoGlass Systems",
    location: "Ahmedabad, Gujarat",
    price: 2800,
    priceUnit: "per sqm",
    minOrder: "25 sqm",
    leadTime: "14–18 days",
    description: "Double glazed IGU with 12mm air gap and Low-E coating. U-value 1.4 W/m²K — significantly reduces heating and cooling costs. Ideal for energy-efficient commercial buildings and green building ratings.",
    tags: ["IGU", "Low-E", "energy efficient", "5+12+5", "commercial", "LEED", "green building", "thermal", "insulated", "double glazed"]
  },
  {
    id: 20,
    name: "Insulated Glass Unit 6+16+6 Argon Filled",
    category: "Insulated Glass Unit",
    thickness: 28,
    size: "Custom up to 3000×2000mm",
    color: "Clear",
    coating: "Soft-coat Low-E on surface 3",
    edge: "Sealed — warm-edge spacer + silicone",
    certification: "EN 1279, IS 13830",
    supplier: "ThermoGlass Systems",
    location: "Ahmedabad, Gujarat",
    price: 3800,
    priceUnit: "per sqm",
    minOrder: "20 sqm",
    leadTime: "16–21 days",
    description: "Premium IGU with argon gas fill and soft-coat Low-E. Warm-edge spacer minimizes thermal bridging. U-value 1.1 W/m²K. Suitable for LEED Platinum and Passive House certified buildings.",
    tags: ["argon", "premium", "6+16+6", "Passive House", "LEED Platinum", "warm edge", "energy", "ultra efficient", "high performance", "soft coat Low-E"]
  },
  {
    id: 21,
    name: "Triple Glazed IGU 4+12+4+12+4",
    category: "Insulated Glass Unit",
    thickness: 36,
    size: "Custom up to 2500×1500mm",
    color: "Clear",
    coating: "Double Low-E",
    edge: "Sealed — warm-edge spacer",
    certification: "EN 1279, Passive House certified",
    supplier: "UltraTherm Glass",
    location: "Pune, Maharashtra",
    price: 5500,
    priceUnit: "per sqm",
    minOrder: "15 sqm",
    leadTime: "21–28 days",
    description: "Triple glazed unit with two air/argon gaps and double Low-E coatings. U-value 0.7 W/m²K — the gold standard for extreme cold climates and ultra-low energy buildings. Maximum noise and thermal insulation.",
    tags: ["triple glazed", "Passive House", "ultra efficient", "extreme climate", "0.7 U-value", "noise", "cold", "premium", "highest performance"]
  },

  // ── MIRRORS ──────────────────────────────────────────────
  {
    id: 22,
    name: "4mm Silver Mirror Glass",
    category: "Mirror",
    thickness: 4,
    size: "2440×1830mm",
    color: "Silver",
    coating: "Copper-free eco-friendly silver backing",
    edge: "Polished / Bevelled (optional)",
    certification: "IS 4897",
    supplier: "ReflectPro India",
    location: "Jaipur, Rajasthan",
    price: 380,
    priceUnit: "per sqm",
    minOrder: "30 sqm",
    leadTime: "5–7 days",
    description: "High-quality silver mirror with copper-free backing for superior edge resistance and long life. Available with bevelled edges for premium look. Ideal for bathrooms, dressing rooms, salons, and retail displays.",
    tags: ["mirror", "silver", "bathroom", "dressing", "salon", "retail", "bevelled", "copper free", "eco", "IS 4897"]
  },
  {
    id: 23,
    name: "6mm Antique Bronze Mirror",
    category: "Mirror",
    thickness: 6,
    size: "Custom up to 2440×1500mm",
    color: "Antique bronze / aged",
    coating: "Bronze-tinted reflective backing",
    edge: "Polished / Bevelled",
    certification: "IS 4897",
    supplier: "ArtMirror India",
    location: "Jaipur, Rajasthan",
    price: 850,
    priceUnit: "per sqm",
    minOrder: "10 sqm",
    leadTime: "7–10 days",
    description: "Antique bronze aged-effect mirror glass for luxury interiors, restaurants, boutique hotels, and decorative feature walls. Gives a warm, vintage reflective quality that normal mirrors cannot replicate.",
    tags: ["antique", "bronze", "mirror", "luxury", "hotel", "restaurant", "decorative", "vintage", "feature wall", "interior design"]
  },
  {
    id: 24,
    name: "Smart Switchable Privacy Mirror Glass",
    category: "Mirror",
    thickness: 8,
    size: "Custom up to 2000×1200mm",
    color: "Clear / Mirror (switchable)",
    coating: "PDLC liquid crystal film",
    edge: "Polished",
    certification: "CE, RoHS",
    supplier: "SmartGlass India",
    location: "Bengaluru, Karnataka",
    price: 8500,
    priceUnit: "per sqm",
    minOrder: "5 sqm",
    leadTime: "21–30 days",
    description: "Electrically switchable glass that alternates between clear and mirror/frosted states at the flick of a switch. Perfect for luxury bathrooms, boardroom privacy, showrooms, and smart homes.",
    tags: ["smart glass", "switchable", "privacy", "PDLC", "electric", "luxury", "boardroom", "showroom", "smart home", "mirror", "frosted"]
  },

  // ── SPECIALITY GLASS ─────────────────────────────────────
  {
    id: 25,
    name: "Fire-Rated Glass 30-Minute (EW30)",
    category: "Fire Rated Glass",
    thickness: 10,
    size: "Custom up to 1800×900mm",
    color: "Clear",
    coating: "Fire-resistant intumescent interlayer",
    edge: "Polished",
    certification: "IS 14900, EN 357, EW30",
    supplier: "FireSafe Glazing India",
    location: "Mumbai, Maharashtra",
    price: 6500,
    priceUnit: "per sqm",
    minOrder: "5 sqm",
    leadTime: "21–28 days",
    description: "30-minute fire-rated laminated glass. Intumescent interlayer activates on heat exposure, blocking flames and radiant heat. Mandatory for fire escape routes, stairwells, and buildings with fire safety compliance requirements.",
    tags: ["fire rated", "EW30", "safety", "fire escape", "stairwell", "intumescent", "compliance", "NBC", "mandatory", "fire protection"]
  },
  {
    id: 26,
    name: "Bulletproof Laminated Glass Level BR2",
    category: "Security Glass",
    thickness: 25,
    size: "Custom up to 2100×1200mm",
    color: "Clear",
    coating: "Multi-layer PVB laminate",
    edge: "Polished",
    certification: "EN 1063 BR2, IS 2553",
    supplier: "ShieldGlass India",
    location: "Delhi NCR",
    price: 22000,
    priceUnit: "per sqm",
    minOrder: "5 sqm",
    leadTime: "30–45 days",
    description: "Multi-layer ballistic-resistant laminated glass certified to EN 1063 BR2 level. Stops 9mm handgun rounds. Used in banks, jewellery stores, VIP vehicles, embassies, and high-security facilities.",
    tags: ["bulletproof", "ballistic", "security", "bank", "jewellery", "VIP", "embassy", "BR2", "high security", "protection"]
  },
  {
    id: 27,
    name: "6mm Anti-Reflective (AR) Glass",
    category: "Speciality Glass",
    thickness: 6,
    size: "Custom up to 2440×1500mm",
    color: "Ultra clear",
    coating: "Multi-layer anti-reflective sol-gel coating",
    edge: "Polished",
    certification: "IS 2835, <1% reflectance",
    supplier: "OpticsGlass India",
    location: "Hyderabad, Telangana",
    price: 3200,
    priceUnit: "per sqm",
    minOrder: "10 sqm",
    leadTime: "14–21 days",
    description: "Less than 1% light reflectance — nearly invisible glass. Ideal for museum display cases protecting artwork, retail showcases, picture framing, TV studio teleprompters, and solar panel covers.",
    tags: ["anti reflective", "AR glass", "museum", "showcase", "display", "optical", "low reflectance", "retail", "artwork", "invisible"]
  },
  {
    id: 28,
    name: "Textured Patterned Glass — Chinchilla",
    category: "Decorative Glass",
    thickness: 4,
    size: "2440×1220mm",
    color: "Clear / White",
    coating: "Rolled texture pattern",
    edge: "Cut",
    certification: "IS 5437",
    supplier: "PatternGlass India",
    location: "Firozabad, UP",
    price: 320,
    priceUnit: "per sqm",
    minOrder: "50 sqm",
    leadTime: "5–7 days",
    description: "Chinchilla pattern rolled glass provides excellent light diffusion and privacy. The distinctive pebble-like texture is perfect for bathroom windows, decorative panels, cabinet doors, and interior partitions.",
    tags: ["textured", "patterned", "chinchilla", "bathroom", "cabinet", "decorative", "privacy", "diffused", "rolled", "interior"]
  },
  {
    id: 29,
    name: "Solar Control Low-E Coated Glass",
    category: "Coated Glass",
    thickness: 6,
    size: "3300×2140mm",
    color: "Slight blue-green tint",
    coating: "Online pyrolytic Low-E (hard coat)",
    edge: "Cut",
    certification: "IS 2835, EN 673",
    supplier: "EnergyGlass India",
    location: "Surat, Gujarat",
    price: 890,
    priceUnit: "per sqm",
    minOrder: "100 sqm",
    leadTime: "7–10 days",
    description: "Hard-coat pyrolytic Low-E glass that can be cut and tempered. Reduces solar heat gain (SHGC 0.35) while maintaining good visible light transmission. Ideal for commercial windows and energy-efficient residential projects.",
    tags: ["Low-E", "solar control", "energy efficient", "SHGC", "commercial", "hard coat", "pyrolytic", "window", "heat reduction", "green building"]
  },
  {
    id: 30,
    name: "Lacquered Back-Painted Glass — White",
    category: "Decorative Glass",
    thickness: 6,
    size: "Custom up to 3000×2000mm",
    color: "Gloss White (RAL 9010)",
    coating: "High-temperature baked lacquer",
    edge: "Polished",
    certification: "IS 2835",
    supplier: "ChromaGlass India",
    location: "Ahmedabad, Gujarat",
    price: 1100,
    priceUnit: "per sqm",
    minOrder: "15 sqm",
    leadTime: "10–14 days",
    description: "Back-painted glass with high-gloss lacquer finish for kitchen splashbacks, feature walls, retail displays, and modern interior design. Scratch-resistant, moisture-proof, easy to clean, and available in any RAL colour.",
    tags: ["back painted", "lacquered", "kitchen splashback", "feature wall", "white", "gloss", "interior", "retail", "moisture proof", "modern"]
  },

  // ── HARDWARE & FITTINGS ──────────────────────────────────
  {
    id: 31,
    name: "Stainless Steel Glass Door Patch Fitting Set",
    category: "Hardware",
    thickness: null,
    size: "For glass 8–12mm thick",
    color: "Brushed SS 304",
    coating: "Satin finish SS 304",
    edge: null,
    certification: "IS 1570 (SS 304)",
    supplier: "AlloyFit Hardware",
    location: "Delhi NCR",
    price: 4500,
    priceUnit: "per set (pair)",
    minOrder: "5 sets",
    leadTime: "5–7 days",
    description: "Heavy-duty SS 304 patch fittings for frameless glass doors. Includes floor spring, top pivot, patch plates, and strike plate. Supports glass weight up to 80kg per door leaf. CE certified mechanism.",
    tags: ["hardware", "patch fitting", "glass door", "frameless", "stainless steel", "SS 304", "floor spring", "pivot", "fitting", "door hardware"]
  },
  {
    id: 32,
    name: "Aluminium U-Channel Glass Railing System",
    category: "Hardware",
    thickness: null,
    size: "For 10–12mm glass, length per metre",
    color: "Anodised silver / powder coated",
    coating: "Powder coated (any RAL)",
    edge: null,
    certification: "IS 1948",
    supplier: "ProfileSystems India",
    location: "Pune, Maharashtra",
    price: 850,
    priceUnit: "per running metre",
    minOrder: "20 metres",
    leadTime: "7–10 days",
    description: "Aluminium U-channel base shoe profile for frameless glass balcony railings. Accepts 10–12mm glass. Powder coated in any colour. Easy installation with core-drill anchoring system.",
    tags: ["U-channel", "railing", "balcony", "aluminium", "frameless", "base shoe", "profile", "balustrade", "hardware", "powder coated"]
  },
  {
    id: 33,
    name: "Spider Fitting Point Fixed System (4-way)",
    category: "Hardware",
    thickness: null,
    size: "4-way spider, 135° arms",
    color: "Brushed SS 316",
    coating: "Marine grade SS 316",
    edge: null,
    certification: "IS 1570 (SS 316)",
    supplier: "SpiderGlaze Systems",
    location: "Pune, Maharashtra",
    price: 3200,
    priceUnit: "per spider fitting",
    minOrder: "10 fittings",
    leadTime: "10–14 days",
    description: "Marine-grade SS 316 4-way spider fittings for point-fixed structural glass facades. Articulating arms accommodate glass movement. Suitable for exterior curtain walls, canopies, and wet/coastal environments.",
    tags: ["spider fitting", "point fixed", "facade", "curtain wall", "canopy", "SS 316", "marine grade", "structural", "exterior", "coastal"]
  },
  {
    id: 34,
    name: "UPVC Window System with IGU",
    category: "Window System",
    thickness: null,
    size: "Custom sizes, casement/sliding",
    color: "White / Woodgrain",
    coating: "UPVC with double gasket seal",
    edge: null,
    certification: "IS 14734, CE marked",
    supplier: "WinPro Systems",
    location: "Chennai, Tamil Nadu",
    price: 3500,
    priceUnit: "per sqm (installed)",
    minOrder: "10 sqm",
    leadTime: "21–30 days",
    description: "Complete UPVC window system with 5+12+5 IGU. Factory-fabricated, weather-sealed, and thermally broken. Includes hardware, handles, and installation accessories. Ideal for residential and hospitality projects.",
    tags: ["UPVC", "window system", "complete", "installed", "residential", "hospitality", "casement", "sliding", "weather sealed", "thermal break"]
  },
  {
    id: 35,
    name: "Glass Clamp Spider Point Fitting (Round)",
    category: "Hardware",
    thickness: null,
    size: "For glass 6–12mm",
    color: "Polished chrome / Brushed SS",
    coating: "Chrome plated / SS 304",
    edge: null,
    certification: "IS 1570",
    supplier: "AlloyFit Hardware",
    location: "Delhi NCR",
    price: 650,
    priceUnit: "per piece",
    minOrder: "20 pieces",
    leadTime: "5–7 days",
    description: "Round glass clamp fittings for point-fixed glazing, glass shelves, display cases, and shower enclosures. Available in polished chrome and brushed stainless finish. Suitable for 6mm to 12mm glass.",
    tags: ["clamp", "point fixed", "glass shelf", "display", "shower", "chrome", "fitting", "hardware", "round", "stainless"]
  },

  // ── MORE SPECIALITY ──────────────────────────────────────
  {
    id: 36,
    name: "Toughened Glass Balustrade Panel",
    category: "Tempered Glass",
    thickness: 10,
    size: "1100×900mm (standard panel)",
    color: "Clear",
    coating: "None",
    edge: "Polished all edges",
    certification: "IS 2553, Building Regs Part K",
    supplier: "BaluGlass India",
    location: "Bengaluru, Karnataka",
    price: 1350,
    priceUnit: "per panel",
    minOrder: "10 panels",
    leadTime: "10–14 days",
    description: "Pre-cut and polished toughened glass balustrade panels for staircase handrails and terrace railings. Standard 1100mm height per building regulations. Ready for direct installation with post or channel system.",
    tags: ["balustrade", "staircase", "handrail", "railing", "terrace", "pre-cut", "clear", "10mm", "toughened", "ready to install"]
  },
  {
    id: 37,
    name: "6mm Digitally Printed Glass",
    category: "Decorative Glass",
    thickness: 6,
    size: "Custom up to 2440×1500mm",
    color: "Any custom design",
    coating: "Ceramic frit digital print (kiln-fired)",
    edge: "Polished",
    certification: "IS 2835, UV stable inks",
    supplier: "PrintGlass Studio",
    location: "Bengaluru, Karnataka",
    price: 2800,
    priceUnit: "per sqm",
    minOrder: "5 sqm",
    leadTime: "14–21 days",
    description: "Custom digitally printed glass with UV-stable ceramic frit inks fired into glass surface. Print fades never — not a film or vinyl. Used for corporate branding, decorative facades, hospital wayfinding, and feature partitions.",
    tags: ["printed", "digital print", "custom", "branding", "logo", "decorative", "facade", "ceramic frit", "permanent", "hospital", "corporate"]
  },
  {
    id: 38,
    name: "Rooflight / Skylight Laminated Glass Unit",
    category: "Laminated Glass",
    thickness: 13.52,
    size: "Custom up to 3000×1500mm",
    color: "Clear",
    coating: "SGP interlayer + UV filter",
    edge: "Polished, structural silicone ready",
    certification: "IS 2553, BS EN 14449, overhead glazing certified",
    supplier: "SkylightGlass India",
    location: "Mumbai, Maharashtra",
    price: 3200,
    priceUnit: "per sqm",
    minOrder: "10 sqm",
    leadTime: "14–21 days",
    description: "Overhead laminated glass certified for skylight and rooflight use. SGP interlayer provides post-breakage integrity — glass stays in place even after cracking. UV filter protects interiors. Slope-ready with structural silicone edge preparation.",
    tags: ["skylight", "rooflight", "overhead", "laminated", "SGP", "UV filter", "structural", "roof", "natural light", "safety"]
  },
  {
    id: 39,
    name: "Curved Tempered Glass Panel",
    category: "Tempered Glass",
    thickness: 8,
    size: "Custom radius, up to 2400mm length",
    color: "Clear",
    coating: "None",
    edge: "Polished",
    certification: "IS 2553",
    supplier: "BendGlass India",
    location: "Surat, Gujarat",
    price: 4200,
    priceUnit: "per sqm",
    minOrder: "10 sqm",
    leadTime: "21–30 days",
    description: "Curved / bent tempered glass for circular showcases, curved facades, cylindrical buildings, and architectural feature elements. Custom radius from 600mm. Consistent curvature across the full panel.",
    tags: ["curved", "bent", "circular", "showcase", "architectural", "feature", "cylindrical", "custom radius", "tempered", "specialty"]
  },
  {
    id: 40,
    name: "Solar Panel Cover Glass (AR Coated)",
    category: "Speciality Glass",
    thickness: 3.2,
    size: "1650×992mm (standard solar module)",
    color: "Ultra clear",
    coating: "Anti-reflective + anti-soiling coating",
    edge: "Arrised",
    certification: "IEC 61215, IEC 61730, IS 2835",
    supplier: "SolarGlass India",
    location: "Surat, Gujarat",
    price: 680,
    priceUnit: "per panel",
    minOrder: "100 panels",
    leadTime: "10–14 days",
    description: "Specially engineered low-iron AR-coated glass for solar PV modules. 94% light transmission maximises energy yield. Anti-soiling coating reduces dust accumulation. IEC certified for 25+ year outdoor durability.",
    tags: ["solar", "photovoltaic", "PV", "anti reflective", "low iron", "solar panel", "energy", "rooftop", "renewable", "IEC certified"]
  }
];
